### se pueden agregar mas de un request en un solo archivo 
POST https://mongo-render-0a62.onrender.com/api/notes
Content-Type: application/json

{
    
}
### para obtener todas las notas desde el servidor
GET https://mongo-render-0a62.onrender.com/api/notes

### 
POST https://mongo-render-0a62.onrender.com/api/notesmejorado
Content-Type: application/json

{
    "content":"con render",
    "important":true  
}
